/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rkhis
 */
public class banjir2View extends javax.swing.JFrame {

    /**
     * Creates new form banjir2View
     */
    public banjir2View() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
      public void KembaliMouseListener(MouseListener l) {
        this.kembali.addMouseListener(l);
    }

    public JButton getKembali() {
        return kembali;
    }

    public void setKembali(JButton kembali) {
        this.kembali = kembali;
    }

    public void setButton_dada(JButton Button_dada) {
        this.Button_dada = Button_dada;
    }

    public void setButton_kaki(JButton Button_kaki) {
        this.Button_kaki = Button_kaki;
    }

    public void setButton_lutut(JButton Button_lutut) {
        this.Button_lutut = Button_lutut;
    }

    public void setButton_tangan(JButton Button_tangan) {
        this.Button_tangan = Button_tangan;
    }

    public void DadaMouseListener(MouseListener l) {
        this.Button_dada.addMouseListener(l);
    }

    public void KakiMouseListener(MouseListener l) {
        this.Button_kaki.addMouseListener(l);
    }

    public void LututMouseListener(MouseListener l) {
        this.Button_lutut.addMouseListener(l);
    }

    public void TanganMouseListener(MouseListener l) {
        this.Button_tangan.addMouseListener(l);
    }

    public JLabel getLabel_darah() {
        return Label_darah;
    }

    public void setLabel_darah(JLabel Label_darah) {
        this.Label_darah = Label_darah;
    }

    public JLabel getLabel_timer() {
        return Label_timer;
    }

    public void setLabel_timer(JLabel Label_timer) {
        this.Label_timer = Label_timer;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_timer = new javax.swing.JLabel();
        Button_dada = new javax.swing.JButton();
        Button_kaki = new javax.swing.JButton();
        Button_lutut = new javax.swing.JButton();
        Button_tangan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        Label_darah = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_timer.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Label_timer.setForeground(new java.awt.Color(153, 0, 0));
        Label_timer.setText("0");
        getContentPane().add(Label_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 60));

        Button_dada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Banjir2/opt-dada.png"))); // NOI18N
        Button_dada.setBorderPainted(false);
        Button_dada.setContentAreaFilled(false);
        Button_dada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_dada.setFocusable(false);
        getContentPane().add(Button_dada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 580, 140, 150));

        Button_kaki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Banjir2/opt-kaki.png"))); // NOI18N
        Button_kaki.setBorderPainted(false);
        Button_kaki.setContentAreaFilled(false);
        Button_kaki.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_kaki.setFocusable(false);
        getContentPane().add(Button_kaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 140, 150));

        Button_lutut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Banjir2/opt-lutut.png"))); // NOI18N
        Button_lutut.setBorderPainted(false);
        Button_lutut.setContentAreaFilled(false);
        Button_lutut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_lutut.setFocusable(false);
        getContentPane().add(Button_lutut, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 580, 140, 150));

        Button_tangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Banjir2/opt-tangan.png"))); // NOI18N
        Button_tangan.setBorderPainted(false);
        Button_tangan.setContentAreaFilled(false);
        Button_tangan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_tangan.setFocusable(false);
        getContentPane().add(Button_tangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 140, 150));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/level3/btn-Kembali.png"))); // NOI18N
        kembali.setBorder(null);
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, -1, -1));

        Label_darah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/100_.png"))); // NOI18N
        getContentPane().add(Label_darah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Banjir2/bajirframe.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(banjir2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(banjir2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(banjir2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(banjir2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new banjir2View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_dada;
    private javax.swing.JButton Button_kaki;
    private javax.swing.JButton Button_lutut;
    private javax.swing.JButton Button_tangan;
    private javax.swing.JLabel Label_darah;
    private javax.swing.JLabel Label_timer;
    private javax.swing.JLabel bg;
    private javax.swing.JButton kembali;
    // End of variables declaration//GEN-END:variables
}
