/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Image;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author adheraprabu
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form v_home
     */
    public HomeView() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_play = new javax.swing.JButton();
        Button_Bantuan = new javax.swing.JButton();
        Button_Tentang = new javax.swing.JButton();
        Button_keluar = new javax.swing.JButton();
        Button_gantiPassword = new javax.swing.JButton();
        Button_sound = new javax.swing.JButton();
        Label_profilUser = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-main.png"))); // NOI18N
        Button_play.setBorderPainted(false);
        Button_play.setContentAreaFilled(false);
        Button_play.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_play.setFocusable(false);
        Button_play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_play.setMinimumSize(new java.awt.Dimension(150, 60));
        Button_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_playActionPerformed(evt);
            }
        });
        getContentPane().add(Button_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 120, 55));

        Button_Bantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-help.png"))); // NOI18N
        Button_Bantuan.setBorderPainted(false);
        Button_Bantuan.setContentAreaFilled(false);
        Button_Bantuan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Bantuan.setFocusable(false);
        getContentPane().add(Button_Bantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 140, 60));

        Button_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-about.png"))); // NOI18N
        Button_Tentang.setBorderPainted(false);
        Button_Tentang.setContentAreaFilled(false);
        Button_Tentang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Tentang.setFocusable(false);
        getContentPane().add(Button_Tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 660, 140, 60));

        Button_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-exit.png"))); // NOI18N
        Button_keluar.setBorder(null);
        Button_keluar.setBorderPainted(false);
        Button_keluar.setContentAreaFilled(false);
        Button_keluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_keluar.setFocusable(false);
        getContentPane().add(Button_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 60));

        Button_gantiPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-gantipassword.png"))); // NOI18N
        Button_gantiPassword.setBorderPainted(false);
        Button_gantiPassword.setContentAreaFilled(false);
        Button_gantiPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_gantiPassword.setFocusable(false);
        getContentPane().add(Button_gantiPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, -1, -1));

        Button_sound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-sound.png"))); // NOI18N
        Button_sound.setBorderPainted(false);
        Button_sound.setContentAreaFilled(false);
        Button_sound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_sound.setFocusable(false);
        getContentPane().add(Button_sound, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 60, -1));

        Label_profilUser.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 14)); // NOI18N
        Label_profilUser.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(Label_profilUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 40, 90, 20));

        Background.setBackground(new java.awt.Color(255, 102, 102));
        Background.setForeground(new java.awt.Color(255, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/bg-Home.png"))); // NOI18N
        Background.setOpaque(true);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void PlayMouseListener(MouseListener l) {
        this.Button_play.addMouseListener(l);
    }

    public void TentangMouseListener(MouseListener l) {
        this.Button_Tentang.addMouseListener(l);
    }

    public void KeluarMouseListener(MouseListener l) {
        this.Button_keluar.addMouseListener(l);
    }

    public void BantuanMouseListener(MouseListener l) {
        this.Button_Bantuan.addMouseListener(l);
    }

    public void GantiPasswordMouseListener(MouseListener l) {
        this.Button_gantiPassword.addMouseListener(l);
    }

    public void SoundMouseListener(MouseListener l) {
        this.Button_sound.addMouseListener(l);
    }

    public JButton getButton_Bantuan() {
        return Button_Bantuan;
    }

    public void setButton_Bantuan(JButton Button_Bantuan) {
        this.Button_Bantuan = Button_Bantuan;
    }

    public JButton getButton_Tentang() {
        return Button_Tentang;
    }

    public void setButton_Tentang(JButton Button_Tentang) {
        this.Button_Tentang = Button_Tentang;
    }

    public JButton getButton_keluar() {
        return Button_keluar;
    }

    public void setButton_keluar(JButton Button_keluar) {
        this.Button_keluar = Button_keluar;
    }

    public JButton getButton_play() {
        return Button_play;
    }

    public void setButton_play(JButton Button_play) {
        this.Button_play = Button_play;
    }

    public JButton getButton_gantiPassword() {
        return Button_gantiPassword;
    }

    public void setButton_gantiPassword(JButton Button_gantiPassword) {
        this.Button_gantiPassword = Button_gantiPassword;
    }

    public JButton getButton_sound() {
        return Button_sound;
    }

    public void setButton_sound(JButton Button_sound) {
        this.Button_sound = Button_sound;
    }

    public JLabel getLabel_profilUser() {
        return Label_profilUser;
    }

    public void setLabel_profilUser(JLabel Label_profilUser) {
        this.Label_profilUser = Label_profilUser;
    }

    
    private void Button_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_playActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Bantuan;
    private javax.swing.JButton Button_Tentang;
    private javax.swing.JButton Button_gantiPassword;
    private javax.swing.JButton Button_keluar;
    private javax.swing.JButton Button_play;
    private javax.swing.JButton Button_sound;
    private javax.swing.JLabel Label_profilUser;
    // End of variables declaration//GEN-END:variables
}
