/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form v_home
     */
    public HomeView() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_play = new javax.swing.JButton();
        Button_Bantuan = new javax.swing.JButton();
        Button_Tentang = new javax.swing.JButton();
        Button_keluar = new javax.swing.JButton();
        Label_level1 = new javax.swing.JLabel();
        Label_level2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-main.png"))); // NOI18N
        Button_play.setBorderPainted(false);
        Button_play.setContentAreaFilled(false);
        Button_play.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button_play.setMinimumSize(new java.awt.Dimension(150, 60));
        Button_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_playActionPerformed(evt);
            }
        });
        getContentPane().add(Button_play, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 660, 120, 50));

        Button_Bantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-help.png"))); // NOI18N
        Button_Bantuan.setBorderPainted(false);
        Button_Bantuan.setContentAreaFilled(false);
        getContentPane().add(Button_Bantuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 140, 50));

        Button_Tentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-about.png"))); // NOI18N
        Button_Tentang.setBorderPainted(false);
        Button_Tentang.setContentAreaFilled(false);
        getContentPane().add(Button_Tentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 660, 140, 50));

        Button_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/btn-exit.png"))); // NOI18N
        Button_keluar.setBorder(null);
        Button_keluar.setBorderPainted(false);
        Button_keluar.setContentAreaFilled(false);
        getContentPane().add(Button_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 60));

        Label_level1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_level1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/icon-lvl1.png"))); // NOI18N
        Label_level1.setOpaque(true);
        Label_level1.setRequestFocusEnabled(false);
        Label_level1.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(Label_level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 45, 180, 200));

        Label_level2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_level2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/icon-lvl2.png"))); // NOI18N
        Label_level2.setOpaque(true);
        getContentPane().add(Label_level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 50, 180, 200));

        Background.setBackground(new java.awt.Color(255, 102, 102));
        Background.setForeground(new java.awt.Color(255, 204, 204));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Home/bg-Home.png"))); // NOI18N
        Background.setOpaque(true);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void PlayListener(ActionListener l) {
        this.Button_play.addActionListener(l);
    }
    
    public void PlayMouseListener(MouseListener l) {
        this.Button_play.addMouseListener(l);
    }

    public void TentangListener(ActionListener l) {
        this.Button_Tentang.addActionListener(l);
    }
    
    public void TentangMouseListener(MouseListener l) {
        this.Button_Tentang.addMouseListener(l);
    }
    
    public void KeluarListener(ActionListener l) {
        this.Button_keluar.addActionListener(l);
    }
    
    public void KeluarMouseListener(MouseListener l) {
        this.Button_keluar.addMouseListener(l);
    }
    public void BantuanListener(ActionListener l) {
        this.Button_Bantuan.addActionListener(l);
    }
    public void BantuanMouseListener(MouseListener l) {
        this.Button_Bantuan.addMouseListener(l);
    }
    
    public JButton getButton_Bantuan() {
        return Button_Bantuan;
    }

    public void setButton_Bantuan(JButton Button_Bantuan) {
        this.Button_Bantuan = Button_Bantuan;
    }

    public JButton getButton_Tentang() {
        return Button_Tentang;
    }

    public void setButton_Tentang(JButton Button_Tentang) {
        this.Button_Tentang = Button_Tentang;
    }

    public JButton getButton_keluar() {
        return Button_keluar;
    }

    public void setButton_keluar(JButton Button_keluar) {
        this.Button_keluar = Button_keluar;
    }

    public JButton getButton_play() {
        return Button_play;
    }

    public void setButton_play(JButton Button_play) {
        this.Button_play = Button_play;
    }
    
    
            
    private void Button_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_playActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_playActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton Button_Bantuan;
    private javax.swing.JButton Button_Tentang;
    private javax.swing.JButton Button_keluar;
    private javax.swing.JButton Button_play;
    private javax.swing.JLabel Label_level1;
    private javax.swing.JLabel Label_level2;
    // End of variables declaration//GEN-END:variables
}
