/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rkhis
 */
public class kebakaran1View extends javax.swing.JFrame {

    /**
     * Creates new form kebakaran1View
     */
    public kebakaran1View() {
        initComponents();
        setLocationRelativeTo(this);
    }
    public void GasListener(MouseListener l) {
        this.gas_button.addMouseListener(l);
    }
    public void LapListener(MouseListener l) {
        this.lap_button.addMouseListener(l);
    }
    public void AirListener(MouseListener l) {
        this.air_button.addMouseListener(l);
    }
    
    public void setDynamic_Panel(JPanel dynamic_Panel) {
        this.dynamic_Panel = dynamic_Panel;
    }
    
    public JPanel getDynamic_Panel() {
        return dynamic_Panel;
    }

    public JButton getGas_button() {
        return gas_button;
    }

    public void setGas_button(JButton gas_button) {
        this.gas_button = gas_button;
    }

    public JButton getAir_button() {
        return air_button;
    }

    public void setAir_button(JButton air_button) {
        this.air_button = air_button;
    }

    public JButton getLap_button() {
        return lap_button;
    }

    public void setLap_button(JButton lap_button) {
        this.lap_button = lap_button;
    }
    public JLabel getLabel_darah() {
        return darah;
    }

    public void setLabel_darah(JLabel darah) {
        this.darah = darah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        darah = new javax.swing.JLabel();
        dynamic_Panel = new javax.swing.JPanel();
        api = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lap_button = new javax.swing.JButton();
        air_button = new javax.swing.JButton();
        gas_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        darah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/100_.png"))); // NOI18N
        getContentPane().add(darah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        dynamic_Panel.setOpaque(false);
        getContentPane().add(dynamic_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 570));

        api.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/api.gif"))); // NOI18N
        getContentPane().add(api, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -140, -1, 710));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        lap_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-KainBasah.png"))); // NOI18N
        lap_button.setBorder(null);
        lap_button.setBorderPainted(false);
        lap_button.setContentAreaFilled(false);
        lap_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(lap_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, 140, 160));

        air_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-Air.png"))); // NOI18N
        air_button.setBorder(null);
        air_button.setBorderPainted(false);
        air_button.setContentAreaFilled(false);
        air_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(air_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 580, 140, 160));

        gas_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-Gas.png"))); // NOI18N
        gas_button.setBorder(null);
        gas_button.setBorderPainted(false);
        gas_button.setContentAreaFilled(false);
        gas_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(gas_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 580, 140, 160));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/panel.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1200, 180));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton air_button;
    private javax.swing.JLabel api;
    private javax.swing.JLabel darah;
    private javax.swing.JPanel dynamic_Panel;
    private javax.swing.JButton gas_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lap_button;
    // End of variables declaration//GEN-END:variables
}
