/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rkhis
 */
public class Kebakaran2View extends javax.swing.JFrame {

    /**
     * Creates new form Kebakaran2View
     */
    public Kebakaran2View() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void KembaliMouseListener(MouseListener l) {
        this.kembali.addMouseListener(l);
    }

    public JLabel getLabel_darah() {
        return Label_darah;
    }

    public void setLabel_darah(JLabel Label_darah) {
        this.Label_darah = Label_darah;
    }

    public JButton getKembali() {
        return kembali;
    }

    public void setKembali(JButton kembali) {
        this.kembali = kembali;
    }
    
    public void AirMaduLidahMouseListener(MouseListener l) {
        this.Button_AitMaduLidah.addMouseListener(l);
    }
    public void EsBatuMouseListener(MouseListener l) {
        this.Button_EsBatu.addMouseListener(l);
    }
    public void PastaMouseListener(MouseListener l) {
        this.Button_PastaGigi.addMouseListener(l);
    }

    public JLabel getLabel_timer() {
        return Label_timer;
    }

    public void setLabel_timer(JLabel Label_timer) {
        this.Label_timer = Label_timer;
    }

    public JButton getButton_AitMaduLidah() {
        return Button_AitMaduLidah;
    }

    public void setButton_AitMaduLidah(JButton Button_AitMaduLidah) {
        this.Button_AitMaduLidah = Button_AitMaduLidah;
    }

    public JButton getButton_EsBatu() {
        return Button_EsBatu;
    }

    public void setButton_EsBatu(JButton Button_EsBatu) {
        this.Button_EsBatu = Button_EsBatu;
    }

    public JButton getButton_PastaGigi() {
        return Button_PastaGigi;
    }

    public void setButton_PastaGigi(JButton Button_PastaGigi) {
        this.Button_PastaGigi = Button_PastaGigi;
    }

    public JLabel getBg() {
        return bg;
    }

    public void setBg(JLabel bg) {
        this.bg = bg;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_timer = new javax.swing.JLabel();
        Button_EsBatu = new javax.swing.JButton();
        Button_PastaGigi = new javax.swing.JButton();
        Button_AitMaduLidah = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        Label_darah = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_timer.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        Label_timer.setForeground(new java.awt.Color(255, 204, 0));
        Label_timer.setText("0");
        getContentPane().add(Label_timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 70, 60));

        Button_EsBatu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-2_1.png"))); // NOI18N
        Button_EsBatu.setBorder(null);
        Button_EsBatu.setBorderPainted(false);
        Button_EsBatu.setContentAreaFilled(false);
        Button_EsBatu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_EsBatu.setFocusable(false);
        getContentPane().add(Button_EsBatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 290, -1, -1));

        Button_PastaGigi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-3_1.png"))); // NOI18N
        Button_PastaGigi.setBorder(null);
        Button_PastaGigi.setBorderPainted(false);
        Button_PastaGigi.setContentAreaFilled(false);
        Button_PastaGigi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_PastaGigi.setFocusable(false);
        getContentPane().add(Button_PastaGigi, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, -1, -1));

        Button_AitMaduLidah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/opt-1_1.png"))); // NOI18N
        Button_AitMaduLidah.setBorder(null);
        Button_AitMaduLidah.setBorderPainted(false);
        Button_AitMaduLidah.setContentAreaFilled(false);
        Button_AitMaduLidah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_AitMaduLidah.setFocusable(false);
        getContentPane().add(Button_AitMaduLidah, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 140, 160));

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/level3/btn-Kembali.png"))); // NOI18N
        kembali.setBorder(null);
        kembali.setBorderPainted(false);
        kembali.setContentAreaFilled(false);
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        Label_darah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/100_.png"))); // NOI18N
        getContentPane().add(Label_darah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/kebakaran-frame.gif"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kebakaran2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kebakaran2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kebakaran2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kebakaran2View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kebakaran2View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_AitMaduLidah;
    private javax.swing.JButton Button_EsBatu;
    private javax.swing.JButton Button_PastaGigi;
    private javax.swing.JLabel Label_darah;
    private javax.swing.JLabel Label_timer;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton kembali;
    // End of variables declaration//GEN-END:variables
}
