/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rkhis
 */
public class LevelKuisView extends javax.swing.JFrame {

    /**
     * Creates new form LevelKuis
     */
    public LevelKuisView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_soal = new javax.swing.JLabel();
        Button_jawabB = new javax.swing.JButton();
        Button_jawabC = new javax.swing.JButton();
        Button_jawabA = new javax.swing.JButton();
        Button_jawabD = new javax.swing.JButton();
        Button_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_soal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_soal.setText("Ini adalah contoh soal dari kuis MECIN LEVEL 3, Ini adalah contoh soal dari kuis MECIN LEVEL 3, Ini adalah contoh soal dari kuis MECIN LEVEL 3");
        getContentPane().add(Label_soal, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 179, 752, 92));

        Button_jawabB.setText("JAWABAN 2");
        getContentPane().add(Button_jawabB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 188, 79));

        Button_jawabC.setText("JAWABAN 3");
        getContentPane().add(Button_jawabC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 188, 79));

        Button_jawabA.setText("JAWABAN 1");
        getContentPane().add(Button_jawabA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 188, 79));

        Button_jawabD.setText("JAWABAN 4");
        getContentPane().add(Button_jawabD, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 188, 79));

        Button_back.setText("BACK");
        getContentPane().add(Button_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 730));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("KESEMPATAN :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 145, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void BackMouseListener(MouseListener l) {
        this.Button_back.addMouseListener(l);
    }

    public JButton getButton_back() {
        return Button_back;
    }

    public void setButton_back(JButton Button_back) {
        this.Button_back = Button_back;
    }

    public JButton getButton_jawabA() {
        return Button_jawabA;
    }

    public void setButton_jawabA(JButton Button_jawabA) {
        this.Button_jawabA = Button_jawabA;
    }

    public JButton getButton_jawabB() {
        return Button_jawabB;
    }

    public void setButton_jawabB(JButton Button_jawabB) {
        this.Button_jawabB = Button_jawabB;
    }

    public JButton getButton_jawabC() {
        return Button_jawabC;
    }

    public void setButton_jawabC(JButton Button_jawabC) {
        this.Button_jawabC = Button_jawabC;
    }

    public JButton getButton_jawabD() {
        return Button_jawabD;
    }

    public void setButton_jawabD(JButton Button_jawabD) {
        this.Button_jawabD = Button_jawabD;
    }

    public JLabel getLabel_soal() {
        return Label_soal;
    }

    public void setLabel_soal(JLabel Label_soal) {
        this.Label_soal = Label_soal;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelKuisView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_back;
    private javax.swing.JButton Button_jawabA;
    private javax.swing.JButton Button_jawabB;
    private javax.swing.JButton Button_jawabC;
    private javax.swing.JButton Button_jawabD;
    private javax.swing.JLabel Label_soal;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
