/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author rkhis
 */
public class MenangKuisView extends javax.swing.JFrame {

    /**
     * Creates new form MenangKuisView
     */
    public MenangKuisView() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    public void OK(MouseListener l) {
        this.Button_ok.addMouseListener(l);
    }
    public void Reload(MouseListener l) {
        this.Button_re.addMouseListener(l);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_nama = new javax.swing.JLabel();
        Label_jawabanSalah = new javax.swing.JLabel();
        Label_jawabanBenar = new javax.swing.JLabel();
        Label_Skor = new javax.swing.JLabel();
        Label_SkorTertinggi = new javax.swing.JLabel();
        Button_ok = new javax.swing.JButton();
        Button_re = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_nama.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        Label_nama.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_nama.setText("sd");
        getContentPane().add(Label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 120, 40));

        Label_jawabanSalah.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        Label_jawabanSalah.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(Label_jawabanSalah, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 408, 60, 30));

        Label_jawabanBenar.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        Label_jawabanBenar.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(Label_jawabanBenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 367, 60, 30));

        Label_Skor.setFont(new java.awt.Font("Comic Sans MS", 1, 55)); // NOI18N
        Label_Skor.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(Label_Skor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 80, 60));

        Label_SkorTertinggi.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        Label_SkorTertinggi.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(Label_SkorTertinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 295, 60, 50));

        Button_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/level3/btnHome.png"))); // NOI18N
        Button_ok.setBorder(null);
        Button_ok.setBorderPainted(false);
        Button_ok.setContentAreaFilled(false);
        Button_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_okActionPerformed(evt);
            }
        });
        getContentPane().add(Button_ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        Button_re.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/level3/btnRe.png"))); // NOI18N
        Button_re.setBorder(null);
        Button_re.setBorderPainted(false);
        Button_re.setContentAreaFilled(false);
        getContentPane().add(Button_re, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 500, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/level3/win (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_okActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenangKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenangKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenangKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenangKuisView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenangKuisView().setVisible(true);
            }
        });
    }

    public JLabel getLabel_nama() {
        return Label_nama;
    }

    public void setLabel_nama(JLabel Label_nama) {
        this.Label_nama = Label_nama;
    }
    
    
    public JLabel getLabel_Skor() {
        return Label_Skor;
    }

    public void setLabel_Skor(JLabel Label_Skor) {
        this.Label_Skor = Label_Skor;
    }

    public JButton getButton_ok() {
        return Button_ok;
    }

    public void setButton_ok(JButton Button_ok) {
        this.Button_ok = Button_ok;
    }

    public JButton getButton_re() {
        return Button_re;
    }

    public void setButton_re(JButton Button_re) {
        this.Button_re = Button_re;
    }
    
    
    public JLabel getLabel_SkorTertinggi() {
        return Label_SkorTertinggi;
    }

    public void setLabel_SkorTertinggi(JLabel Label_SkorTertinggi) {
        this.Label_SkorTertinggi = Label_SkorTertinggi;
    }

    public JLabel getLabel_jawabanBenar() {
        return Label_jawabanBenar;
    }

    public void setLabel_jawabanBenar(JLabel Label_jawabanBenar) {
        this.Label_jawabanBenar = Label_jawabanBenar;
    }

    public JLabel getLabel_jawabanSalah() {
        return Label_jawabanSalah;
    }

    public void setLabel_jawabanSalah(JLabel Label_jawabanSalah) {
        this.Label_jawabanSalah = Label_jawabanSalah;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

//    public JLabel getjLabel2() {
//        return jLabel2;
//    }
//
//    public void setjLabel2(JLabel jLabel2) {
//        this.jLabel2 = jLabel2;
//    }
//
//    public JLabel getjLabel3() {
//        return jLabel3;
//    }
//
//    public void setjLabel3(JLabel jLabel3) {
//        this.jLabel3 = jLabel3;
//    }
//
//    public JLabel getjLabel4() {
//        return jLabel4;
//    }
//
//    public void setjLabel4(JLabel jLabel4) {
//        this.jLabel4 = jLabel4;
//    }
//
//    public JLabel getjLabel5() {
//        return jLabel5;
//    }
//
//    public void setjLabel5(JLabel jLabel5) {
//        this.jLabel5 = jLabel5;
//    }
//
//    public JLabel getjLabel6() {
//        return jLabel6;
//    }
//
//    public void setjLabel6(JLabel jLabel6) {
//        this.jLabel6 = jLabel6;
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_ok;
    private javax.swing.JButton Button_re;
    private javax.swing.JLabel Label_Skor;
    private javax.swing.JLabel Label_SkorTertinggi;
    private javax.swing.JLabel Label_jawabanBenar;
    private javax.swing.JLabel Label_jawabanSalah;
    private javax.swing.JLabel Label_nama;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
