/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class PilihanLevelView extends javax.swing.JFrame {

    /**
     * Creates new form PilihanLevelView
     */
    public PilihanLevelView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    public void Level1MouseListener(MouseListener l) {
        this.Button_Level1.addMouseListener(l);
    }
    public void KuisMouseListener(MouseListener l) {
        this.Button_kuis.addMouseListener(l);
    }
    public void KembaliMouseListener(MouseListener l) {
        this.Button_kembali.addMouseListener(l);
    }

    public JButton getButton_kembali() {
        return Button_kembali;
    }

    public void setButton_kembali(JButton Button_kembali) {
        this.Button_kembali = Button_kembali;
    }
    

    public void Banjir1MouseListener(MouseListener l) {
        this.Button_Banjir1.addMouseListener(l);
    }

    public void Gempa1MouseListener(MouseListener l) {
        this.Button_gempa1.addMouseListener(l);
    }

    public void Kebakaran1MouseListener(MouseListener l) {
        this.Button_kebakaran1.addMouseListener(l);
    }

    public void Level2MouseListener(MouseListener l) {
        this.Button_Level2.addMouseListener(l);
    }

    public void Banjir2MouseListener(MouseListener l) {
        this.Button_Banjir2.addMouseListener(l);
    }

    public void Gempa2MouseListener(MouseListener l) {
        this.Button_gempa2.addMouseListener(l);
    }

    public void Kebakaran2MouseListener(MouseListener l) {
        this.Button_kebakaran2.addMouseListener(l);
    }

    public JButton getButton_Banjir1() {
        return Button_Banjir1;
    }

    public void setButton_Banjir1(JButton Button_Banjir1) {
        this.Button_Banjir1 = Button_Banjir1;
    }

    public JButton getButton_Banjir2() {
        return Button_Banjir2;
    }

    public void setButton_Banjir2(JButton Button_Banjir2) {
        this.Button_Banjir2 = Button_Banjir2;
    }

    public JButton getButton_Level1() {
        return Button_Level1;
    }

    public void setButton_Level1(JButton Button_Level1) {
        this.Button_Level1 = Button_Level1;
    }

    public JButton getButton_Level2() {
        return Button_Level2;
    }

    public void setButton_Level2(JButton Button_Level2) {
        this.Button_Level2 = Button_Level2;
    }

    public JButton getButton_gempa1() {
        return Button_gempa1;
    }

    public void setButton_gempa1(JButton Button_gempa1) {
        this.Button_gempa1 = Button_gempa1;
    }

    public JButton getButton_gempa2() {
        return Button_gempa2;
    }

    public void setButton_gempa2(JButton Button_gempa2) {
        this.Button_gempa2 = Button_gempa2;
    }

    public JButton getButton_kebakaran1() {
        return Button_kebakaran1;
    }

    public void setButton_kebakaran1(JButton Button_kebakaran1) {
        this.Button_kebakaran1 = Button_kebakaran1;
    }

    public JButton getButton_kuis() {
        return Button_kuis;
    }

    public void setButton_kuis(JButton Button_kuis) {
        this.Button_kuis = Button_kuis;
    }
    
    public JButton getButton_kebakaran2() {
        return Button_kebakaran2;
    }

    public void setButton_kebakaran2(JButton Button_kebakaran2) {
        this.Button_kebakaran2 = Button_kebakaran2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_kembali = new javax.swing.JButton();
        Button_kuis = new javax.swing.JButton();
        Button_Level1 = new javax.swing.JButton();
        Button_Banjir1 = new javax.swing.JButton();
        Button_gempa1 = new javax.swing.JButton();
        Button_kebakaran1 = new javax.swing.JButton();
        Button_Level2 = new javax.swing.JButton();
        Button_kebakaran2 = new javax.swing.JButton();
        Button_Banjir2 = new javax.swing.JButton();
        Button_gempa2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/About/btn-back.png"))); // NOI18N
        Button_kembali.setBorderPainted(false);
        Button_kembali.setContentAreaFilled(false);
        Button_kembali.setFocusable(false);
        getContentPane().add(Button_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        Button_kuis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/lvl-3.png"))); // NOI18N
        Button_kuis.setBorder(null);
        Button_kuis.setBorderPainted(false);
        Button_kuis.setContentAreaFilled(false);
        Button_kuis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_kuis.setFocusable(false);
        getContentPane().add(Button_kuis, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        Button_Level1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/lvl-1.png"))); // NOI18N
        Button_Level1.setBorderPainted(false);
        Button_Level1.setContentAreaFilled(false);
        Button_Level1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Level1.setFocusable(false);
        getContentPane().add(Button_Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        Button_Banjir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-Banjir.png"))); // NOI18N
        Button_Banjir1.setBorderPainted(false);
        Button_Banjir1.setContentAreaFilled(false);
        Button_Banjir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Banjir1.setFocusable(false);
        getContentPane().add(Button_Banjir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, -1, -1));

        Button_gempa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-gempa.png"))); // NOI18N
        Button_gempa1.setBorderPainted(false);
        Button_gempa1.setContentAreaFilled(false);
        Button_gempa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_gempa1.setFocusable(false);
        getContentPane().add(Button_gempa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, -1, -1));

        Button_kebakaran1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-kebakar.png"))); // NOI18N
        Button_kebakaran1.setBorderPainted(false);
        Button_kebakaran1.setContentAreaFilled(false);
        Button_kebakaran1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_kebakaran1.setFocusable(false);
        getContentPane().add(Button_kebakaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, -1, -1));

        Button_Level2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/lvl-2.png"))); // NOI18N
        Button_Level2.setBorderPainted(false);
        Button_Level2.setContentAreaFilled(false);
        Button_Level2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Level2.setFocusable(false);
        getContentPane().add(Button_Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 190, -1));

        Button_kebakaran2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-kebakar.png"))); // NOI18N
        Button_kebakaran2.setBorderPainted(false);
        Button_kebakaran2.setContentAreaFilled(false);
        Button_kebakaran2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_kebakaran2.setFocusable(false);
        getContentPane().add(Button_kebakaran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 500, -1, -1));

        Button_Banjir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-Banjir.png"))); // NOI18N
        Button_Banjir2.setBorderPainted(false);
        Button_Banjir2.setContentAreaFilled(false);
        Button_Banjir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Banjir2.setFocusable(false);
        getContentPane().add(Button_Banjir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        Button_gempa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-gempa.png"))); // NOI18N
        Button_gempa2.setBorderPainted(false);
        Button_gempa2.setContentAreaFilled(false);
        Button_gempa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_gempa2.setFocusable(false);
        getContentPane().add(Button_gempa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/bg-Level.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Banjir1;
    private javax.swing.JButton Button_Banjir2;
    private javax.swing.JButton Button_Level1;
    private javax.swing.JButton Button_Level2;
    private javax.swing.JButton Button_gempa1;
    private javax.swing.JButton Button_gempa2;
    private javax.swing.JButton Button_kebakaran1;
    private javax.swing.JButton Button_kebakaran2;
    private javax.swing.JButton Button_kembali;
    private javax.swing.JButton Button_kuis;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
