/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author adheraprabu
 */
public class PilihanLevelView extends javax.swing.JFrame {

    /**
     * Creates new form PilihanLevelView
     */
    public PilihanLevelView() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Level1 = new javax.swing.JButton();
        Button_Banjir1 = new javax.swing.JButton();
        Button_gempa1 = new javax.swing.JButton();
        Button_kebakaran1 = new javax.swing.JButton();
        Button_Level2 = new javax.swing.JButton();
        Button_kebakaran2 = new javax.swing.JButton();
        Button_Banjir2 = new javax.swing.JButton();
        Button_gempa2 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Level1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/lvl-1.png"))); // NOI18N
        Button_Level1.setBorderPainted(false);
        Button_Level1.setContentAreaFilled(false);
        getContentPane().add(Button_Level1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        Button_Banjir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-Banjir.png"))); // NOI18N
        Button_Banjir1.setBorderPainted(false);
        Button_Banjir1.setContentAreaFilled(false);
        getContentPane().add(Button_Banjir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        Button_gempa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-gempa.png"))); // NOI18N
        Button_gempa1.setBorderPainted(false);
        Button_gempa1.setContentAreaFilled(false);
        getContentPane().add(Button_gempa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        Button_kebakaran1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-kebakar.png"))); // NOI18N
        Button_kebakaran1.setBorderPainted(false);
        Button_kebakaran1.setContentAreaFilled(false);
        getContentPane().add(Button_kebakaran1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        Button_Level2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/lvl-2.png"))); // NOI18N
        Button_Level2.setBorderPainted(false);
        Button_Level2.setContentAreaFilled(false);
        getContentPane().add(Button_Level2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        Button_kebakaran2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-kebakar.png"))); // NOI18N
        Button_kebakaran2.setBorderPainted(false);
        Button_kebakaran2.setContentAreaFilled(false);
        getContentPane().add(Button_kebakaran2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, -1, -1));

        Button_Banjir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-Banjir.png"))); // NOI18N
        Button_Banjir2.setBorderPainted(false);
        Button_Banjir2.setContentAreaFilled(false);
        getContentPane().add(Button_Banjir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        Button_gempa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/sub-gempa.png"))); // NOI18N
        Button_gempa2.setBorderPainted(false);
        Button_gempa2.setContentAreaFilled(false);
        getContentPane().add(Button_gempa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, -1));

        bg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Level/bg-Level.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Banjir1;
    private javax.swing.JButton Button_Banjir2;
    private javax.swing.JButton Button_Level1;
    private javax.swing.JButton Button_Level2;
    private javax.swing.JButton Button_gempa1;
    private javax.swing.JButton Button_gempa2;
    private javax.swing.JButton Button_kebakaran1;
    private javax.swing.JButton Button_kebakaran2;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
