/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author adheraprabu
 */
public class PopUpLoginView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpLogin
     */
    public PopUpLoginView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public void BatalMouseListener(MouseListener l) {
        this.Button_Batal.addMouseListener(l);
    }

    public void MasukMouseListener(MouseListener l) {
        this.Button_Masuk.addMouseListener(l);
    }

    public JButton getButton_Batal() {
        return Button_Batal;
    }

    public void setButton_Batal(JButton Button_Batal) {
        this.Button_Batal = Button_Batal;
    }

    public JButton getButton_Masuk() {
        return Button_Masuk;
    }

    public void setButton_Masuk(JButton Button_Masuk) {
        this.Button_Masuk = Button_Masuk;
    }

    public JPasswordField getPasswordField_Password() {
        return PasswordField_Password;
    }

    public void setPasswordField_Password(JPasswordField PasswordField_Password) {
        this.PasswordField_Password = PasswordField_Password;
    }

    public JTextField getTextField_Username() {
        return TextField_Username;
    }

    public void setTextField_Username(JTextField TextField_Username) {
        this.TextField_Username = TextField_Username;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Masuk = new javax.swing.JButton();
        Button_Batal = new javax.swing.JButton();
        TextField_Username = new javax.swing.JTextField();
        PasswordField_Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(null);
        setModalityType(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/btn-Masuk.png"))); // NOI18N
        Button_Masuk.setBorderPainted(false);
        Button_Masuk.setContentAreaFilled(false);
        Button_Masuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Masuk.setFocusable(false);
        getContentPane().add(Button_Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 140, -1));

        Button_Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/btn-Batal.png"))); // NOI18N
        Button_Batal.setBorderPainted(false);
        Button_Batal.setContentAreaFilled(false);
        Button_Batal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button_Batal.setFocusable(false);
        getContentPane().add(Button_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 140, -1));

        TextField_Username.setBorder(null);
        getContentPane().add(TextField_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 440, 50));

        PasswordField_Password.setBorder(null);
        PasswordField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordField_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordField_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 440, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/PopUp-Login.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasswordField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordField_PasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Batal;
    private javax.swing.JButton Button_Masuk;
    private javax.swing.JPasswordField PasswordField_Password;
    private javax.swing.JTextField TextField_Username;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
