/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;
import javax.swing.JButton;

/**
 *
 * @author adheraprabu
 */
public class PopupKeluarView extends javax.swing.JDialog {

    /**
     * Creates new form PopupKeluarView
     */
    public PopupKeluarView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public void YaMouseListener(MouseListener l) {
        this.Button_ya.addMouseListener(l);
    }

    public void TidakMouseListener(MouseListener l) {
        this.Button_tidak.addMouseListener(l);
    }

    public JButton getButton_tidak() {
        return Button_tidak;
    }

    public void setButton_tidak(JButton Button_tidak) {
        this.Button_tidak = Button_tidak;
    }

    public JButton getButton_ya() {
        return Button_ya;
    }

    public void setButton_ya(JButton Button_ya) {
        this.Button_ya = Button_ya;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_tidak = new javax.swing.JButton();
        Button_ya = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(null);
        setModalityType(null);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ExitPopUp/btn-tidak.png"))); // NOI18N
        Button_tidak.setBorderPainted(false);
        Button_tidak.setContentAreaFilled(false);
        Button_tidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_tidakActionPerformed(evt);
            }
        });
        getContentPane().add(Button_tidak, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        Button_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ExitPopUp/btn-ya.png"))); // NOI18N
        Button_ya.setBorderPainted(false);
        Button_ya.setContentAreaFilled(false);
        Button_ya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_yaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_ya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/ExitPopUp/PopUp-Exit.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_tidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_tidakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_tidakActionPerformed

    private void Button_yaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_yaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_yaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_tidak;
    private javax.swing.JButton Button_ya;
    private javax.swing.JLabel bg;
    // End of variables declaration//GEN-END:variables
}
