/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.MouseListener;

/**
 *
 * @author adheraprabu
 */
public class PopUpLoginView extends javax.swing.JDialog {

    /**
     * Creates new form PopUpLogin
     */
    public PopUpLoginView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public void BatalMouseListener(MouseListener l) {
        this.Button_Batal.addMouseListener(l);
    }

    public void MasukMouseListener(MouseListener l) {
        this.Button_Masuk.addMouseListener(l);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Masuk = new javax.swing.JButton();
        Button_Batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModalExclusionType(null);
        setModalityType(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Masuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/btn-Masuk.png"))); // NOI18N
        Button_Masuk.setBorderPainted(false);
        Button_Masuk.setContentAreaFilled(false);
        getContentPane().add(Button_Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 140, -1));

        Button_Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/btn-Batal.png"))); // NOI18N
        Button_Batal.setBorderPainted(false);
        Button_Batal.setContentAreaFilled(false);
        getContentPane().add(Button_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 140, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/RegisterandLogin/PopUp-Login.png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Batal;
    private javax.swing.JButton Button_Masuk;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
